--Diamond--

local item = "diamonds"

print("How many ".. item, " do you want to make?")

local input = tonumber( read())

for input = 1,(input) do
	turtle.select(1)
	turtle.suck()
	turtle.drop(turtle.getItemCount(1)-input)
	turtle.select(2)
	turtle.suck()
	turtle.drop(turtle.getItemCount(2)-input)
	turtle.select(3)
	turtle.suck()
	turtle.drop(turtle.getItemCount(3)-input)
	turtle.select(5)
	turtle.suck()
	turtle.drop(turtle.getItemCount(5)-input)
	turtle.select(6)
	turtle.suck()
	turtle.drop(turtle.getItemCount(6)-input)
	turtle.select(7)
	turtle.suck()
	turtle.drop(turtle.getItemCount(7)-input)
	turtle.select(9)
	turtle.suck()
	turtle.drop(turtle.getItemCount(9)-input)
	turtle.select(10)
	turtle.suck()
	turtle.drop(turtle.getItemCount(10)-input)
	turtle.select(11)
	turtle.suck()
	turtle.drop(turtle.getItemCount(11)-input)
	turtle.select(4)
	turtle.drop()
	turtle.select(8)
	turtle.drop()
	turtle.select(12)
	turtle.drop()
	turtle.select(13)
	turtle.drop()
	turtle.select(14)
	turtle.drop()
	turtle.select(15)
	turtle.drop()
	turtle.select(16)
	turtle.drop()
end

turtle.craft()
turtle.turnRight()
turtle.turnRight()
turtle.select(4)
turtle.drop()
turtle.select(8)
turtle.drop()
turtle.select(12)
turtle.drop()
turtle.select(13)
turtle.drop()
turtle.select(14)
turtle.drop()
turtle.select(15)
turtle.drop()
turtle.select(16)
turtle.drop()
turtle.turnRight()
turtle.turnRight()
